name: Kilted Docker Push

on:
  release:
    types: [published]

jobs:
  kilted_docker_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag name
        run: |
          tag_name=$(git describe --tags --abbrev=0 HEAD^)
          echo "tag_name=$tag_name" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker
        uses: docker/build-push-action@v6
        with:
          build-args: ROS_DISTRO=kilted
          push: true
          tags: mgons/audio_common:kilted-${{ github.event.release.tag_name }}
